"""add unified knowledge resources

Revision ID: 255a21876da7
Revises: e9c1d9871470
Create Date: 2026-08-28 00:27:33.107996
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '255a21876da7'
down_revision: str | Sequence[str] | None = 'e9c1d9871470'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('resource_type', sa.Enum('script', 'store_rule', 'faq', 'activity', 'other', name='knowledge_resource_type'), server_default='other', nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='knowledge_document_status'), server_default='active', nullable=False),
    sa.Column('active_version_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_documents'))
    )
    op.create_index(op.f('ix_knowledge_documents_store_id'), 'knowledge_documents', ['store_id'], unique=False)
    op.create_index('ix_knowledge_documents_store_status', 'knowledge_documents', ['store_id', 'status'], unique=False)
    op.create_table('knowledge_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('version_label', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('uploading', 'uploaded', 'processing', 'ready', 'failed', name='knowledge_version_status'), server_default='uploading', nullable=False),
    sa.Column('manifest_key', sa.String(length=1024), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('total_size', sa.BigInteger(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], name=op.f('fk_knowledge_versions_document_id_knowledge_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_versions')),
    sa.UniqueConstraint('document_id', 'version_label', name='uq_knowledge_versions_document_version')
    )
    op.create_index(op.f('ix_knowledge_versions_document_id'), 'knowledge_versions', ['document_id'], unique=False)
    op.create_foreign_key(
        'fk_knowledge_documents_active_version_id_knowledge_versions',
        'knowledge_documents',
        'knowledge_versions',
        ['active_version_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_table('knowledge_files',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('client_file_id', sa.String(length=120), nullable=False),
    sa.Column('relative_path', sa.String(length=1024), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('last_modified', sa.BigInteger(), nullable=False),
    sa.Column('etag', sa.String(length=128), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'verified', name='knowledge_file_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['knowledge_versions.id'], name=op.f('fk_knowledge_files_version_id_knowledge_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_files')),
    sa.UniqueConstraint('object_key', name='uq_knowledge_files_object_key'),
    sa.UniqueConstraint('version_id', 'client_file_id', name='uq_knowledge_files_version_client'),
    sa.UniqueConstraint('version_id', 'relative_path', name='uq_knowledge_files_version_path')
    )
    op.create_index(op.f('ix_knowledge_files_version_id'), 'knowledge_files', ['version_id'], unique=False)
    op.create_table('knowledge_upload_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'expired', name='knowledge_upload_session_status'), server_default='active', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['knowledge_versions.id'], name=op.f('fk_knowledge_upload_sessions_version_id_knowledge_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_upload_sessions'))
    )
    op.create_index(op.f('ix_knowledge_upload_sessions_expires_at'), 'knowledge_upload_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_knowledge_upload_sessions_version_id'), 'knowledge_upload_sessions', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_upload_sessions_version_id'), table_name='knowledge_upload_sessions')
    op.drop_index(op.f('ix_knowledge_upload_sessions_expires_at'), table_name='knowledge_upload_sessions')
    op.drop_table('knowledge_upload_sessions')
    op.drop_index(op.f('ix_knowledge_files_version_id'), table_name='knowledge_files')
    op.drop_table('knowledge_files')
    op.drop_constraint(
        'fk_knowledge_documents_active_version_id_knowledge_versions',
        'knowledge_documents',
        type_='foreignkey',
    )
    op.drop_index(op.f('ix_knowledge_versions_document_id'), table_name='knowledge_versions')
    op.drop_table('knowledge_versions')
    op.drop_index('ix_knowledge_documents_store_status', table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_store_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    sa.Enum(name='knowledge_upload_session_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='knowledge_file_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='knowledge_version_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='knowledge_document_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='knowledge_resource_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
