"""add dm invites and optional token store

Revision ID: 31a48daa44dd
Revises: b8061aa4f251
Create Date: 2026-08-28 23:28:54.919082
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '31a48daa44dd'
down_revision: str | Sequence[str] | None = 'b8061aa4f251'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), server_default='dm', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_store_invites_created_by_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_store_invites_store_id_stores'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], name=op.f('fk_store_invites_used_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store_invites')),
    sa.UniqueConstraint('code_hash', name=op.f('uq_store_invites_code_hash'))
    )
    op.create_index(op.f('ix_store_invites_store_id'), 'store_invites', ['store_id'], unique=False)
    op.alter_column('refresh_tokens', 'store_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('refresh_tokens', 'store_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_store_invites_store_id'), table_name='store_invites')
    op.drop_table('store_invites')
    # ### end Alembic commands ###
