"""add script visual pipeline

Revision ID: 52916a882eab
Revises: 5e0fcb261249
Create Date: 2026-09-07 23:04:53.735401
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '52916a882eab'
down_revision: str | Sequence[str] | None = '5e0fcb261249'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visual_style_presets',
    sa.Column('id', sa.Uuid(), nullable=False, comment='视觉风格模板ID'),
    sa.Column('store_id', sa.Uuid(), nullable=True, comment='门店ID；为空表示系统内置模板'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模板名称，例如民国悬疑电影感'),
    sa.Column('style_type', sa.String(length=60), nullable=False, comment='风格类型，例如 cinematic, anime, horror, comedy'),
    sa.Column('description', sa.Text(), nullable=True, comment='给店长看的风格说明'),
    sa.Column('prompt_template', sa.Text(), nullable=False, comment='用于拼接最终生图 prompt 的风格模板'),
    sa.Column('negative_prompt', sa.Text(), nullable=True, comment='负向提示词，例如避免文字变形、避免血腥等'),
    sa.Column('recommended_aspect_ratios', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='推荐比例，例如 1:1、3:4、9:16、16:9'),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False, comment='是否系统内置模板'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='是否启用'),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False, comment='排序值，越小越靠前'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_visual_style_presets_store_id_stores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_visual_style_presets'))
    )
    op.create_index('ix_visual_style_presets_store_active', 'visual_style_presets', ['store_id', 'is_active', 'sort_order'], unique=False)
    op.create_table('script_visual_profiles',
    sa.Column('id', sa.Uuid(), nullable=False, comment='剧本视觉档案ID'),
    sa.Column('store_id', sa.Uuid(), nullable=False, comment='门店ID，用于多门店数据隔离'),
    sa.Column('document_id', sa.Uuid(), nullable=False, comment='关联的知识库剧本文档ID'),
    sa.Column('script_profile_id', sa.Uuid(), nullable=True, comment='关联的结构化剧本档案ID，可为空；有剧本档案时优先使用'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='剧本名称'),
    sa.Column('era', sa.String(length=120), nullable=True, comment='时代背景，例如民国上海、现代校园、古风王朝'),
    sa.Column('world_setting', sa.Text(), nullable=True, comment='世界观/故事空间的视觉描述'),
    sa.Column('main_scenes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='核心场景，例如高宅、窗边、旧上海街道、密室、宴会厅'),
    sa.Column('visual_symbols', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='核心视觉符号，例如旗袍、西装、窗户、香烟、窃听器、旧报纸'),
    sa.Column('color_palette', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='推荐主色调，例如深蓝、暗金、酒红、黑色'),
    sa.Column('atmosphere_keywords', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='氛围关键词，例如悬疑、暧昧、压抑、荒诞、欢乐'),
    sa.Column('character_visuals', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='人物视觉设定，例如角色公开身份、服装、道具、情绪；避免写剧透身份'),
    sa.Column('spoiler_safe_rules', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='生图时的剧透安全规则，例如不要暴露凶手、隐藏身份、最终反转'),
    sa.Column('copyright_safe_rules', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='版权安全规则，例如不要复刻发行海报、不要出现原logo、不要照搬人物姿势'),
    sa.Column('reference_image_urls', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='参考图URL，可来自知识库解析出的图片或店长上传图片'),
    sa.Column('confidence_score', sa.Integer(), nullable=True, comment='AI提炼置信度/完整度，0-100'),
    sa.Column('status', sa.String(length=40), server_default='draft', nullable=False, comment='视觉档案状态：draft=草稿，ready=可用，failed=失败，approved=已确认'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='生成失败原因'),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True, comment='触发生成的用户ID'),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True, comment='确认视觉档案的用户ID'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='确认时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_script_visual_profiles_approved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_script_visual_profiles_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], name=op.f('fk_script_visual_profiles_document_id_knowledge_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_profile_id'], ['script_profiles.id'], name=op.f('fk_script_visual_profiles_script_profile_id_script_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_script_visual_profiles_store_id_stores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_script_visual_profiles'))
    )
    op.create_index('ix_script_visual_profiles_store_document', 'script_visual_profiles', ['store_id', 'document_id'], unique=False)
    op.create_index('ix_script_visual_profiles_store_status', 'script_visual_profiles', ['store_id', 'status', 'updated_at'], unique=False)
    op.create_table('script_visual_assets',
    sa.Column('id', sa.Uuid(), nullable=False, comment='视觉素材ID'),
    sa.Column('store_id', sa.Uuid(), nullable=False, comment='门店ID'),
    sa.Column('document_id', sa.Uuid(), nullable=False, comment='关联剧本文档ID'),
    sa.Column('visual_profile_id', sa.Uuid(), nullable=True, comment='关联视觉档案ID'),
    sa.Column('style_preset_id', sa.Uuid(), nullable=True, comment='生成时使用的视觉风格模板ID'),
    sa.Column('usage_type', sa.String(length=60), nullable=False, comment='素材用途：session_cover=拼车主图，session_detail=详情图，moments_poster=朋友圈图，character_portrait=人物图'),
    sa.Column('usage_label', sa.String(length=80), nullable=False, comment='素材用途中文名'),
    sa.Column('prompt', sa.Text(), nullable=False, comment='最终用于生成图片的 prompt'),
    sa.Column('negative_prompt', sa.Text(), nullable=True, comment='负向提示词'),
    sa.Column('aspect_ratio', sa.String(length=20), server_default='1:1', nullable=False, comment='图片比例，例如 1:1、3:4、9:16'),
    sa.Column('object_key', sa.String(length=1024), nullable=True, comment='图片在 OSS 中的 object key'),
    sa.Column('image_url', sa.String(length=2048), nullable=True, comment='图片可访问URL'),
    sa.Column('status', sa.String(length=40), server_default='draft', nullable=False, comment='素材状态：draft=草稿，ready=已生成，failed=失败，selected=已选为正式'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='生成失败原因'),
    sa.Column('is_selected', sa.Boolean(), server_default='false', nullable=False, comment='是否被店长选为正式素材'),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=True, comment='选为正式素材的时间'),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True, comment='创建素材的用户ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_script_visual_assets_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], name=op.f('fk_script_visual_assets_document_id_knowledge_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_script_visual_assets_store_id_stores'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['style_preset_id'], ['visual_style_presets.id'], name=op.f('fk_script_visual_assets_style_preset_id_visual_style_presets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['visual_profile_id'], ['script_visual_profiles.id'], name=op.f('fk_script_visual_assets_visual_profile_id_script_visual_profiles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_script_visual_assets'))
    )
    op.create_index('ix_script_visual_assets_profile_usage', 'script_visual_assets', ['visual_profile_id', 'usage_type', 'is_selected'], unique=False)
    op.create_index('ix_script_visual_assets_store_document', 'script_visual_assets', ['store_id', 'document_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_script_visual_assets_store_document', table_name='script_visual_assets')
    op.drop_index('ix_script_visual_assets_profile_usage', table_name='script_visual_assets')
    op.drop_table('script_visual_assets')
    op.drop_index('ix_script_visual_profiles_store_status', table_name='script_visual_profiles')
    op.drop_index('ix_script_visual_profiles_store_document', table_name='script_visual_profiles')
    op.drop_table('script_visual_profiles')
    op.drop_index('ix_visual_style_presets_store_active', table_name='visual_style_presets')
    op.drop_table('visual_style_presets')
    # ### end Alembic commands ###
