"""restore script profile and opening manual tables

Revision ID: 5e0fcb261249
Revises: 677de57762ab
Create Date: 2026-09-07 18:39:08.879619
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5e0fcb261249'
down_revision: str | Sequence[str] | None = '677de57762ab'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_opening_manuals',
    sa.Column('id', sa.Uuid(), nullable=False, comment='主持人手册ID'),
    sa.Column('store_id', sa.Uuid(), nullable=False, comment='门店ID，用于区分不同门店的数据归属'),
    sa.Column('document_id', sa.Uuid(), nullable=False, comment='知识库文档ID，例如某一个剧本资料'),
    sa.Column('version_id', sa.Uuid(), nullable=True, comment='知识库版本ID，表示该主持人手册基于哪一次上传版本生成'),
    sa.Column('manual_version_no', sa.Integer(), server_default='1', nullable=False, comment='主持人手册版本号，同一剧本可多次生成或迭代'),
    sa.Column('title', sa.String(length=220), nullable=False, comment='主持人手册标题'),
    sa.Column('style', sa.String(length=40), server_default='professional', nullable=False, comment='生成风格：professional=专业版，simple=简洁版，training=培训版'),
    sa.Column('target_dm_level', sa.String(length=40), server_default='newbie', nullable=False, comment='目标DM水平：newbie=新手DM，experienced=熟练DM'),
    sa.Column('extra_requirement', sa.Text(), nullable=True, comment='店长补充要求或迭代意见'),
    sa.Column('outline', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='手册大纲结构，便于前端按章节展示'),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='每个章节的生成结果摘要和状态'),
    sa.Column('timeline', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='开本时间线，用于记录每个阶段的DM动作、玩家动作、物料发放和风险提醒'),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='生成时引用的知识库来源文件列表'),
    sa.Column('markdown_key', sa.String(length=1024), nullable=True, comment='完整Markdown文件在OSS中的存储路径'),
    sa.Column('markdown_preview', sa.Text(), nullable=True, comment='Markdown内容预览，用于列表页快速展示'),
    sa.Column('validation_result', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False, comment='AI或规则校验结果，例如是否缺少流程、话术、风险提示'),
    sa.Column('status', postgresql.ENUM('draft', 'generating', 'ready', 'failed', 'approved', name='opening_manual_status', create_type=False), server_default='draft', nullable=False, comment='生成状态：draft=草稿，generating=生成中，ready=已完成，failed=失败，approved=已确认正式使用'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='生成失败时的错误信息'),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True, comment='触发生成的用户ID'),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True, comment='确认正式使用该手册的用户ID'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='店长确认该手册为正式版本的时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_script_opening_manuals_approved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_script_opening_manuals_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], name=op.f('fk_script_opening_manuals_document_id_knowledge_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_script_opening_manuals_store_id_stores'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['knowledge_versions.id'], name=op.f('fk_script_opening_manuals_version_id_knowledge_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_script_opening_manuals'))
    )
    op.create_index('ix_opening_manuals_status_created', 'script_opening_manuals', ['store_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_opening_manuals_store_document', 'script_opening_manuals', ['store_id', 'document_id', 'created_at'], unique=False)
    op.create_table('script_profiles',
    sa.Column('id', sa.Uuid(), nullable=False, comment='剧本档案ID'),
    sa.Column('store_id', sa.Uuid(), nullable=False, comment='门店ID，用于多门店数据隔离'),
    sa.Column('document_id', sa.Uuid(), nullable=False, comment='关联的知识库文档ID，一般是一套剧本资料'),
    sa.Column('version_id', sa.Uuid(), nullable=True, comment='生成档案时使用的知识库版本ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='剧本正式名称'),
    sa.Column('alias_names', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='剧本别名，方便后续 AI 识别用户口语化搜索'),
    sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='剧本类型中文标签，例如推理、欢乐、机制、变格'),
    sa.Column('player_count_min', sa.Integer(), nullable=True, comment='建议最少玩家数'),
    sa.Column('player_count_max', sa.Integer(), nullable=True, comment='建议最多玩家数'),
    sa.Column('duration_minutes', sa.Integer(), nullable=True, comment='预估开本时长，单位分钟'),
    sa.Column('difficulty', sa.String(length=80), nullable=True, comment='玩家难度，例如新手友好、进阶、硬核'),
    sa.Column('dm_difficulty', sa.String(length=80), nullable=True, comment='DM主持难度，例如新手可开、中等、较难'),
    sa.Column('summary', sa.Text(), nullable=True, comment='玩家可见简介，默认不剧透'),
    sa.Column('story_background', sa.Text(), nullable=True, comment='故事背景摘要，可用于详情页和客服介绍'),
    sa.Column('truth_summary', sa.Text(), nullable=True, comment='真相摘要，含剧透信息，仅后台/DM可见'),
    sa.Column('selling_points', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='玩家可见卖点列表'),
    sa.Column('suitable_players', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='适合玩家画像，例如新手、熟人局、团建、喜欢机制玩家'),
    sa.Column('core_mechanics', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='核心机制/玩法摘要'),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='角色信息草稿，先用JSON保持灵活，后续稳定后可拆角色表'),
    sa.Column('relationships', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='人物关系边，例如 A 与 B 的亲属、恋人、敌对、阵营、秘密等关系'),
    sa.Column('material_checklist', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='开本物料清单'),
    sa.Column('opening_risks', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='开本风险和控场提醒'),
    sa.Column('spoiler_notes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='剧透注意事项，提醒哪些内容不能暴露给玩家'),
    sa.Column('source_chunk_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='生成档案引用的知识库chunk ID列表，便于回溯来源'),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='生成档案引用的来源文件路径'),
    sa.Column('retrieval_diagnostics', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False, comment='剧本档案生成时的多路召回诊断结果，用于排查哪些资料没有命中'),
    sa.Column('confidence_score', sa.Integer(), nullable=True, comment='AI抽取置信度/完整度，0-100'),
    sa.Column('review_status', postgresql.ENUM('draft', 'needs_review', 'approved', 'failed', name='script_profile_review_status', create_type=False), server_default='draft', nullable=False, comment='确认状态：draft=AI草稿，needs_review=需确认，approved=已确认，failed=失败'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='生成失败原因'),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True, comment='触发生成的用户ID'),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True, comment='确认档案正式可用的用户ID'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='确认时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_script_profiles_approved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_script_profiles_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], name=op.f('fk_script_profiles_document_id_knowledge_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_script_profiles_store_id_stores'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['knowledge_versions.id'], name=op.f('fk_script_profiles_version_id_knowledge_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_script_profiles'))
    )
    op.create_index('ix_script_profiles_store_document', 'script_profiles', ['store_id', 'document_id'], unique=False)
    op.create_index(op.f('ix_script_profiles_store_id'), 'script_profiles', ['store_id'], unique=False)
    op.create_index('ix_script_profiles_store_status', 'script_profiles', ['store_id', 'review_status', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_script_profiles_store_status', table_name='script_profiles')
    op.drop_index(op.f('ix_script_profiles_store_id'), table_name='script_profiles')
    op.drop_index('ix_script_profiles_store_document', table_name='script_profiles')
    op.drop_table('script_profiles')
    op.drop_index('ix_opening_manuals_store_document', table_name='script_opening_manuals')
    op.drop_index('ix_opening_manuals_status_created', table_name='script_opening_manuals')
    op.drop_table('script_opening_manuals')
    # ### end Alembic commands ###
