"""create users table

Revision ID: e9c1d9871470
Revises:
Create Date: 2026-08-27 18:53:21.329209
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e9c1d9871470"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "role",
            sa.Enum("admin", "manager", "user", "guest", "dm", name="user_role"),
            server_default="user",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "disabled", "pending", name="user_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("nickname", sa.String(length=50), nullable=True),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("phone_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index("ix_users_role_status", "users", ["role", "status"], unique=False)
    op.create_index("uq_users_phone", "users", ["phone"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_users_phone", table_name="users")
    op.drop_index("ix_users_role_status", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
